const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Flash: 0},
	{Cat: 0},
	{Solid: 0},
	{GreenSolidTiles: 0},
	{BlueSolidTiles: 0},
	{RedSolidTiles: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{PlayerBox: 0},
	{Keyboard: 0},
	{state: 0},
	{Enemy: 0},
	{EdgeMarker: 0},
	{BlueBG: 0},
	{BlueBG2: 0},
	{BlueLevel: 0},
	{Sine: 0},
	{MovingBlue: 0},
	{RedLevel: 0},
	{RedBG: 0},
	{RedBG2: 0},
	{MovingRed: 0},
	{Spikes: 0},
	{GreenLevel: 0},
	{GreenBG2: 0},
	{GreenBG: 0},
	{GreenTiles: 0},
	{BlueTiles: 0},
	{Tilemap: 0}
];

self.InstanceType = {
	Cat: class extends self.ISpriteInstance {},
	GreenSolidTiles: class extends self.ITilemapInstance {},
	BlueSolidTiles: class extends self.ITilemapInstance {},
	RedSolidTiles: class extends self.ITilemapInstance {},
	PlayerBox: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EdgeMarker: class extends self.ISpriteInstance {},
	BlueBG: class extends self.ISpriteInstance {},
	BlueBG2: class extends self.ISpriteInstance {},
	BlueLevel: class extends self.ISpriteInstance {},
	MovingBlue: class extends self.ISpriteInstance {},
	RedLevel: class extends self.ISpriteInstance {},
	RedBG: class extends self.ISpriteInstance {},
	RedBG2: class extends self.ISpriteInstance {},
	MovingRed: class extends self.ISpriteInstance {},
	Spikes: class extends self.ISpriteInstance {},
	GreenLevel: class extends self.ISpriteInstance {},
	GreenBG2: class extends self.ISpriteInstance {},
	GreenBG: class extends self.ISpriteInstance {},
	GreenTiles: class extends self.ITilemapInstance {},
	BlueTiles: class extends self.ITilemapInstance {},
	Tilemap: class extends self.ITilemapInstance {}
}